config/routes.rb
Rails.application.routes.draw do
  resource(:profile, controller: :users, only: %i[show update]) { post :update }
  resources :fallacies, only: :index
end

app/models/concerns/randomizable.rb
module Randomizable
  extend ActiveSupport::Concern

  included do
    scope :random, -> { order 'RANDOM()' }
  end
end

app/models/fallacy.rb
class Fallacy < ActiveRecord::Base
  extend FriendlyId
  include Randomizable

  translates :name, :description, :example, fallbacks_for_empty_translations: true

  has_attached_file    :picture, styles: { original: '200x200>', thumbnail: '64x64' }
  validates_attachment :picture, content_type: { content_type: /\Aimage\// },
                                 size: { in: 0..10.kilobytes }

  delegate :url, to: :picture, prefix: true, allow_nil: true

  def thumbnail_url
    picture_url :thumbnail
  end
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user, inverse_of: :sessions, counter_cache: true, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sessions, inverse_of: :user, dependent: :destroy
  validates_inclusion_of :locale, in: I18n.available_locales.map(&:to_s)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_globals

  private

  def set_globals
    token = session[:token] ||= SecureRandom.hex
    @session = Session.find_or_create_by token: token do |session|
      locale ||= http_accept_language.compatible_language_from I18n.available_locales
      locale ||= I18n.default_locale
      session.build_user guest: true, locale: locale
    end
    @user = @session.user
    I18n.locale = @user.locale
  end
end

app/controllers/fallacies_controller.rb
class FallaciesController < ApplicationController

  def index
    @fallacies = Fallacy.includes(:translations).all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    @user.update params.permit %i(locale)
    redirect_to request.referer || root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def each_locale current_first: false, &block
    locales = current_first ? [I18n.locale] : []
    locales = locales + (I18n.available_locales - locales)
    locales.each { |locale| concat(capture locale, locale == I18n.locale, &block) }
  end

  def navbar_link destination
    name = t destination, scope: :navigation
    options = { class: :current } if controller_path == destination.to_s
    content_tag(:li, options) { link_to name, controller: "/#{destination}" }
  end

end

app/views/fallacies/_fallacy.html.slim
article.column.large-3.medium-6.small-12
  a.thumbnail href='#'
    header.media-object
      .media-object-section
        img.img-circle width='64px' height='64px' src=fallacy.thumbnail_url
      .media-object-section
        h1.lead = fallacy.name
    p = fallacy.description
    p: em = fallacy.example

app/views/fallacies/index.html.slim
section.row == render @fallacies

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    == render 'layouts/head/meta'
    title FallacyMania!
    == stylesheet_link_tag 'application', media: :all
    == csrf_meta_tags
  body
    header == render 'layouts/header/navbar'
    main == yield
    == javascript_include_tag 'application', defer: true

app/views/layouts/head/_meta.html.slim
meta charset='utf-8'
meta name='viewport' content='width=device-width, initial-scale=1'

app/views/layouts/header/_locales.html.slim
= form_tag profile_path
  fieldset.button-group.tiny
    - each_locale current_first: true do |locale, current|
      button.button type='submit' name='locale' value=locale disabled=current = locale

app/views/layouts/header/_navbar.html.slim
aside.title-bar.hide-for-medium data-responsive-toggle='navigation'
  button.menu-icon type='button' data-toggle=true
  .title-bar-title Menu

nav#navigation.top-bar
  ul.menu.top-bar-left.vertical.medium-horizontal
    / li.menu-text: strong.top-bar-title: a href=root_path FallacyMania!
    li: a href=root_path FallacyMania!
    = navbar_link :fallacies
  ul.menu.top-bar-right
    li == render 'layouts/header/locales'
    li: a Sign Up / Log In

app/views/pages/home.html.slim
.jumbotron
  h1 Welcome to FallacyMania!
  p
    | FallacyMania is a game intent to learn, remember, understand and resist fallacies you meet everyday in a real life.
    br
    | You read the statement, and try to guess which fallacy is there.
  p
    em
      ' Sorry, site in construction for awhile!
      ' But you can take a look at the
      => link_to 'fallacies list', fallacies_path
      | right now.

app/views/pages/index.html.slim
.jumbotron
  h1 Welcome to FallacyMania!
  p
    | FallacyMania is a game intent to learn, remember, understand and resist fallacies you meet everyday in a real life.
    br
    | You read the statement, and try to guess which fallacy is there.
  p
    em
      ' Sorry, site in construction for awhile!
      ' But you can take a look at the
      => link_to 'fallacies list', fallacies_path
      | right now.